package com.example.petproject.enums;

public enum ApiErrorCode {
    // Default
    NOT_FOUND,
    AUTHENTICATION_ERROR,
    WRONG_JWT_TYPE_FOR_REQUEST_EXCEPTION,
    UNLOGGED_USER_EXCEPTION,
    CURRENT_USER_PLATFORM_IS_BLOCKED,
    USER_IN_BLACK_LIST_EXCEPTION,
    CURRENT_USER_DEVICE_IS_REMOVED,
    INTERNAL_SERVER_ERROR,
    NOT_IMPLEMENTED,
    BAD_REQUEST,
    REMOTE_SYSTEM_RESPONSE_ERROR,
    VALIDATION_EXCEPTION,

    // confirmation
    CONFIRM_VERIFICATION_EXCEPTION,
    CONFIRMATION_CODE_EXPIRED,
    CONFIRMATION_CODE_NOT_VALID,
    CONFIRMATION_CODE_NOT_VALID_AND_BLOCKED,
    CONFIRMATION_TYPE_ERROR,
    CONFIRMATION_PARAMETERS_NOT_VALID,
    CONFIRMATION_PARAMETERS_BAD_REQUEST,

    //product
    CARD_DETAILS_EXCEPTION,

    //product common account
    CARD_ACCOUNT_OVERVIEWS_EXCEPTION,
    UPDATE_STATUS_EXCEPTION,
    UPDATE_BALANCE_EXCEPTION,

    //document
    ADDING_IMAGE_ERROR,
    DOCUMENT_GENERATION_ERROR,
    ADDING_PAGE_NUMBER_ERROR,

    //sc-map
    SC_MAP_EXCEPTION,
    SC_MAP_GET_ACCOUNT_EXCEPTION,
    SC_MAP_SEND_SMS_EXCEPTION,
    SC_MAP_GET_AUTH_TOKEN_EXCEPTION,
    SC_MAP_GET_CREDIT_DETAILS_EXCEPTION,
    SC_MAP_GET_ALL_EXCHANGE_RATES_EXCEPTION,
    SC_MAP_GET_PAIR_EXCHANGE_RATES_EXCEPTION,
    SC_MAP_GET_STATEMENT_EXCEPTION,
    SC_MAP_GET_EMPTY_STATEMENT_EXCEPTION,
    SC_MAP_GET_INTEREST_CALCULATION_INFO_EXCEPTION,
    SC_MAP_GET_CLIENT_EXCEPTION,
    SC_MAP_UPDATE_CLIENT_EXCEPTION,
    SC_MAP_EXECUTE_ACTION_EXCEPTION,
    SC_MAP_ACTION_ATTRIBUTES_EXCEPTION,
    SC_MAP_PRODUCT_BY_CODE_EXCEPTION,
    SC_MAP_DEPOSIT_CALCULATE_INCOME_FORECAST_EXCEPTION,
    SC_MAP_GET_AMOUNT_CURRENT_PAYMENT_BY_CREDIT_EXCEPTION,
    SC_MAP_GET_AMOUNT_FULL_REPAY_AND_DETAILS_EXCEPTION,
    SC_MAP_GET_SMS_SERVICE_STATUS_EXCEPTION,
    SC_MAP_GET_SMS_SERVICE_COST_EXCEPTION,
    SC_MAP_MANAGE_SMS_SERVICE_EXCEPTION,
    SC_MAP_PRODUCT_BALANCE_AMOUNT_EXCEPTION,

    //komplat
    KOMPLAT_EXCEPTION,
    KOMPLAT_GET_CARD_BALANCE_EXCEPTION,
    KOMPLAT_GET_CARD_STATUS_EXCEPTION,
    KOMPLAT_SET_CARD_STATUS_EXCEPTION,
    KOMPLAT_SET_PIN_CVV_CODE_EXCEPTION,
    KOMPLAT_GET_CARD_LIMITS_EXCEPTION,
    KOMPLAT_SET_CARD_LIMITS_EXCEPTION,
    KOMPLAT_GET_PAY_LIST_EXCEPTION,
    KOMPLAT_RUN_OPERATION_EXCEPTION,
    KOMPLAT_CONFIRM_EXCEPTION,
    KOMPLAT_RUN_OPERATION_AND_CONFIRM_EXCEPTION,
    KOMPLAT_GET_PAYMENT_STATUS_EXCEPTION,
    KOMPLAT_GET_OPERATION_HISTORY_EXCEPTION,
    KOMPLAT_GET_CHECK_DUPLICATE_EXCEPTION,
    KOMPLAT_ERROR,
    KOMPLAT_ERROR_195,
    KOMPLAT_ERROR_333,
    KOMPLAT_ERROR_444,
    KOMPLAT_ERROR_500,
    KOMPLAT_ERROR_78299,

    BEPAID_GET_OPERATION_HISTORY_EXCEPTION,
    //bank system
    BANK_SERVICE_EXCEPTION,

    //card
    NO_CARDS_AVAILABLE,
    WRONG_LAST_4_CARD_DIGITS,
    NO_CARD_IN_ACCOUNT,
    GET_ACTION_ATTRIBUTES_EXCEPTION,
    EXECUTE_ACTION_EXCEPTION,
    NOTIFIER_SEND_NOTIFY,
    INCORRECT_BPK_TYPE_FOR_OPENING_CARD,
    PRODUCT_FOR_OPENING_CARD_IS_NULL,
    NO_AVAILABLE_PUBLISHED_CUSTOM_PRODUCTS,

    //sms service
    WRONG_NOTIFY_PRODUCT_EXCEPTION,
    WRONG_USER_PHONE_NUMBER_EXCEPTION,
    WRONG_NOTIFY_PRODUCT_ID_EXCEPTION,
    WRONG_NOTIFY_PRODUCT_IN_LIST_EXCEPTION,
    WRONG_ATTRIBUTE_VALUES_EXCEPTION,
    NOTIFY_PRODUCT_CODE_IS_EMPTY,

    //deposit service
    TOP_UP_DEPOSIT_EXCEPTION,
    WITHDRAWAL_INTEREST_DEPOSIT_EXCEPTIOIN,
    CLOSING_DEPOSIT_NOT_ALLOWED,

    //visa alias
    VISA_ALIAS_ERROR,

    //paritetbank-api
    CASH_INFO_EXCEPTION,

    //action access
    OPENING_CARD_IS_NOT_ALLOWED,
    OPENING_ACCOUNT_IS_NOT_ALLOWED,
    OPENING_DEPOSIT_IS_NOT_ALLOWED,
    OPENING_CREDIT_IS_NOT_ALLOWED,
    BANK_INFO_EXCEPTION,

    ONLINE_CREDIT_SERVICE_EXCEPTION,
    ONLINE_CREDIT_ACTIVE_APPLICATION_EXISTS,
    ONLINE_CREDIT_OFFLINE_APPLICATION_EXISTS,
    ONLINE_CREDIT_CHECK_FAILED,
    ONLINE_CREDIT_CONSENTS_NOT_ACCEPTED
}
